### ISSUE TITLE
缺少初始化sql文件

### ISSUE THREAD

**Issue by glasslion** [Tencent/Metis#15]
安装文档里的下列文件不存在

mysql -umetis -pmetis@123 -h127.0.0.1 metis < /data/Metis/app/sql/time_series_detector/anomaly.sql
mysql -umetis -pmetis@123 -h127.0.0.1 metis < /data/Metis/app/sql/time_series_detector/sample_dataset.sql
mysql -umetis -pmetis@123 -h127.0.0.1 metis < /data/Metis/app/sql/time_series_detector/train_task.sql

**Comment by wanghuaway** [comment]
这些文件是存在的  安装事例中的路径是样例 请更换/data/Metis成服务器存放Metis代码的目录
