### ISSUE TITLE
请问现在支持哪些监控数据源？

### ISSUE THREAD

**Issue by ChanningBJ** [Tencent/Metis#19]

**Comment by zr9558** [comment]
目前 **Metis** 是基于运维场景所形成的学件，其样本来源于内部长期积累的数据。监控的数据包括基础属性 CPU，内存，硬盘等；也包括内部的很多运营数据，例如在线用户数量等。
- 往狭窄的角度来说，可以对海量运维数据进行监控；
- 从宽泛的角度来说，几乎可以对所有时间序列进行监控。

目前内部的时间序列数据是按照分钟来收集的，也就是每一条时间序列的时间戳间隔是一分钟，每一分钟有着对应的一个点。每条时间序列一天将会有1440个点。因此，如果时间间隔是30秒，3分钟，5分钟的话，需要对数据进行必要的改造才能够使用。
