### ISSUE TITLE
特征工程理论依据？

### ISSUE THREAD

**Issue by hanwei36** [Tencent/Metis#21]
有参考什么论文吗？

**Comment by xiaolong2009** [comment]
应该是这个吧
https://conferences2.sigcomm.org/imc/2015/papers/p211.pdf

**Comment by zr9558** [comment]
关于时间序列的文章和资料都比较多：
- 开源工具：tsfresh，https://tsfresh.readthedocs.io/en/latest/
- 论文：清华大学裴丹教授在2015年发表的 [Opprentice](https://conferences2.sigcomm.org/imc/2015/papers/p211.pdf) 系统，其余还有很多的论文。
- blog：
1. [时间序列简介（一）](https://zhuanlan.zhihu.com/p/32584136)

2. [如何理解时间序列？— 从 Riemann 积分和 Lebesgue 积分谈起](https://zhuanlan.zhihu.com/p/34407471)

3. [时间序列的自回归模型—从线性代数的角度来看](https://zhuanlan.zhihu.com/p/35093835)

**Comment by hanwei36** [comment]
多谢解答

**Comment by snowisland1** [comment]
是否有一个方便浏览和学习的，特征工程说明呢？
