### ISSUE TITLE
PolynomialInterpolation代码执行错误

### ISSUE THREAD

**Issue by youngseed88** [Tencent/Metis#22]
在做多项式训练时，x_train和y_train维数明显不对，这块是否代码合入有误

我是单独调用的个函数，估计是X这块没有预处理为903长度；串起来应该没这个问题

**Comment by wanghuaway** [comment]
> 在做多项式训练时，x_train和y_train维数明显不对，这块是否代码合入有误
> 
> 我是单独调用的个函数，估计是X这块没有预处理为903长度；串起来应该没这个问题

![image](https://user-images.githubusercontent.com/42347544/47542346-8b52db00-d90f-11e8-937a-6ac8e85407a3.png)
多项式这里有个默认的窗口长度哈，默认180，所以需要903个数据点，如果要传其他长度的，把window值的参数也带上就可以了
