### ISSUE TITLE
运维学件是已经训练好的，使用自己的样本训练会不会导致学件退化

### ISSUE THREAD

**Issue by wanghuaway** [Tencent/Metis#26]

**Comment by zr9558** [comment]
基于**时间序列异常检测**的场景：

1. 目前 Metis 提供了默认的模型（XGBoost）以及默认的特征层，直接使用就可以进行异常检测；这个也是基于目前 CSIG 运营部海量运营数据和样本数据构建的；
2. 如果不使用默认的模型，那么如果要进行新模型的训练的话，就需要积累一部分的样本数据才可以。
3. 在积累了一部分样本数据之后，对模型的更新就有两种办法。
- （1）基于新的样本数据进行模型的**重新**训练；
- （2）基于新的样本数据进行模型的**增量**训练。
4. 目前 Metis 对外提供的是重新训练的模块，增量训练的模块已经有方案，目前正在走一些学术流程。后续的版本可以支持两种模型更新的办法，也就是重新训练和增量训练都可以。
5. 随着时间的迁移和数据的变化，模型有可能逐渐退化，这种时候就需要更新一次模型。更新模型的办法按照前面两种即可。但是无论使用哪种办法都需要积累样本数据，如果没有样本数据，就没有办法更新模型。
