### ISSUE TITLE
数据采集频率

### ISSUE THREAD

**Issue by hanwei36** [Tencent/Metis#28]
数据采集1秒钟100次左右，样本如何打标和取舍？案例都是一分钟一个点

**Comment by wanghuaway** [comment]
> 数据采集1秒钟100次左右，样本如何打标和取舍？案例都是一分钟一个点

1秒钟100次 那采样周期就是10ms？应该不会有这么细的采样周期吧  如果采样粒度很细，可以采用按1分钟抽样 或者保持窗口值不变调用
