### ISSUE TITLE
请问你们的线上准确率如何呢？

### ISSUE THREAD

**Issue by jimmycui** [Tencent/Metis#31]
请问你们的线上准确率如何呢？

**Comment by zr9558** [comment]
> 请问你们的线上准确率如何呢？

目前 Metis 的时间序列异常检测学件已经在内部大规模使用，已覆盖 20w+ 服务器，承载了 240w+ 业务指标的异常检测。经过了海量监控数据打磨，该学件在异常检测和运维监控领域具有广泛的应用性。经过内部的统计与审核，可以达到线上的准确率>=90%，召回率>=80% 的效果。

**Comment by xiaolong2009** [comment]
线上的模型不是现在默认开放的这个模型吧？

**Comment by zr9558** [comment]
> 线上的模型不是现在默认开放的这个模型吧？

内部的模型一直处于更新和持续迭代中~~~
