### ISSUE TITLE
time_series_detector/common/tsd_common.py bug

### ISSUE THREAD

**Issue by zkybs** [Tencent/Metis#35]
time_series_detector/common/tsd_common.py
normalize_time_series 函数

![image](https://user-images.githubusercontent.com/20988051/48542968-6b557c80-e8fb-11e8-8ec2-2db338664ee4.png)
应该else下面应该也加list类型转换，不然会触发bug

**Comment by wanghuaway** [comment]
else部分本身就是list 所以不需要转换
