### ISSUE TITLE
这个用于异常检测的时候，有监督打标签训练模型环节能否在docker容器环境下使用python调用api来实现？

### ISSUE THREAD

**Issue by yhwmizu** [Tencent/Metis#36]

**Comment by wanghuaway** [comment]
这个也是可以的  虽然打标接口和训练模型接口没有写在接口文档中，前台和后台之间的连接也是通过API来实现的。所以可以调用对应的API，不过打标签（需要看图判断）、训练（需要核对样本个数，来源等）这两个功能直接在web操作友好一些

**Comment by wanghuaway** [comment]
> 那你这个部分的api在部署容器的哪里呀（肯定不是time_series_detector了），方便告知一下准确地址吗

如果是通过docker安装的就在metis-svr中，已经打到镜像里了
如果是手动安装的就用django启动的后端服务中，具体用什么容器也可以根据自己的需要替换
