### ISSUE TITLE
测试集样本怎么去和我的任务ID（模型）匹配

### ISSUE THREAD

**Issue by XQFHNB** [Tencent/Metis#38]
上传测试集样本的时候没有指定任务ID(模型名称)，现在我模型训练后，怎么用测试集去检验我的模型是否达到我的要求？

**Comment by zr9558** [comment]
> 上传测试集样本的时候没有指定任务ID(模型名称)，现在我模型训练后，怎么用测试集去检验我的模型是否达到我的要求？

### 数据划分
通常来说，我们内部做的时候是把人工标记的数据集合分成了四份。这四份数据集合两两交集为空。

| 数据 | label = 1  | label = 0 |
| :------------: |:---------------:|:-----:|
| 训练数据  | 正常样本  | 异常样本 |
| 测试数据 | 正常样本 | 异常样本|

其中，
- 训练数据：包括正常样本和异常样本。是用来模型训练的。
- 测试数据：包括正常样本和异常样本。是用来测试模型效果的。

在这里，我们关注的是异常的情况，也就是更关注 label = 0 的情况。我们自然是希望测试数据中的异常数据都能够被判断为异常，正常数据都能够被判断为正常。所以我们就需要有一些指标来衡量我们**模型的效果**。

### 指标描述
在机器学习领域，我们关注的指标通常有三个，那就是 Recall，Precision，F1-Score。

| True Cases | Prediction Results  |Prediction Results |
| :------------: |:---------------:|:-----:|
|   True Cases | Positive（Prediction Results） | Negative（Prediction Results） |
| Positive（True Cases）  | TP  | FN |
| Negative（True Cases）| FP | TN|

其中，

- Recall = the number of true anomalous points detected / the number of true anomalous points 
= TN / (TN + FP),
- Precision = the number of true anomalous points detected / the number of anomalous points detected
= TN / (TN + FN),
- F1-Score = 2 * precision * recall / (precision + recall).

PS：这个和 wiki 上面的 Recall 和 Precision 略有不同，因为我们关注的是 Negative Label 的情况。

### 上线评估
1. 每次使用训练数据训练完模型之后，需要用测试数据来评价该模型是好是坏，评价的指标就是 Recall 和 Precision。而计算 Recall 和 Precision 的方法就是上面的方法。
2. 上线标准：我们内部的上线标准是准确率 >=90%，召回率>=80% 即可上线。
3. 不同的业务方有着不同的需求，有的时候可能要求准确率高一点，有的时候可能需要召回率高一点。而只要有测试数据，准确率和召回率的指标就可以精确评估出来。根据模型在测试数据上的表现来调整模型即可。

PS: ImageNet 上也有图像领域的训练集合和测试集合，可以参考：http://image-net.org/challenges/LSVRC/2017/
