### ISSUE TITLE
可以提供一下训练接口的参数说明吗？

### ISSUE THREAD

**Issue by zoobree** [Tencent/Metis#40]
是否可以提供一下训练接口的参数说明

**Comment by zr9558** [comment]
> 是否可以提供一下训练接口的参数说明

关于 XGBoost 的训练函数代码在以下链接：
https://github.com/Tencent/Metis/blob/master/time_series_detector/algorithm/xgboosting.py
其中，代码中选定了一些默认的参数值：
```
                 max_depth=10,
                 eta=0.05,
                 gamma=0.1,
                 silent=1,
                 min_child_weight=1,
                 subsample=0.8,
                 colsample_bytree=1,
                 booster='gbtree',
                 objective='binary:logistic',
                 eval_metric='auc'
```
并且在函数` def xgb_train(self, data, task_id, num_round=300)` 中选定了 num_round。关于 XGBoost 的各种参数的解释说明可以参考 XGBoost 的官方文档 https://xgboost.readthedocs.io/en/latest/parameter.html。

**Comment by zoobree** [comment]
不好意思，我想说的是训练的调用接口（输入输出的说明），非算法模型参数。

**Comment by zr9558** [comment]
> 不好意思，我想说的是训练的调用接口（输入输出的说明），非算法模型参数。比如训练data的格式，长度要求，正负样本个数的要求等。
Web 端文档：
https://github.com/Tencent/Metis/blob/master/docs/web_userguide.md
data 的格式详见：
https://github.com/Tencent/Metis/blob/master/docs/api_userguide.md

**Comment by wanghuaway** [comment]
> 不好意思，我想说的是训练的调用接口（输入输出的说明），非算法模型参数。比如训练data的格式，长度要求，正负样本个数的要求等。

def xgb_train(self, data, task_id, num_round=300)
