### ISSUE TITLE
 web上训练任务对用户是不体现任何模型参数的，请问xgb和gbdt是如何选择的？

### ISSUE THREAD

**Issue by zoobree** [Tencent/Metis#41]

**Comment by zr9558** [comment]
目前使用的是 XGBoost，没有使用 GBDT。

**Comment by zoobree** [comment]
后续有考虑在训练任务WEB上加入特征选择/添加、算法选择、模型参数吗？

**Comment by wanghuaway** [comment]
> 后续有考虑在训练任务WEB上加入特征选择/添加、算法选择、模型参数吗？

这个可以的 功能是逐渐丰富完善的  大家如果做了这部分的内容也可以提pr合并进来
