### ISSUE TITLE
为啥率值检测用3-sigma，量值检测用非监督+监督？ 率值是否可以统一到量值这一套框架里面。

### ISSUE THREAD

**Issue by zoobree** [Tencent/Metis#42]

**Comment by wanghuaway** [comment]
因为率值检测从业务场景来看比较单一，一般通常用来检测成功率。用3sigma基本就可以解决，相对来说不需要进行有监督检测。计算量更小，场景更直观单一
如需要有监督其实就等效于量值检测，也可以直接用同一个框架
