### ISSUE TITLE
加载中

### ISSUE THREAD

**Issue by cliffshanghai** [Tencent/Metis#45]
web 界面打开后一直在加载样本数据，不知道哪里出现问题

**Comment by ZhengZhongheng** [comment]
![default](https://user-images.githubusercontent.com/45590585/49431683-09e14900-f7e9-11e8-8454-d05cfc8fbcb8.png)

**Comment by shilicqupt** [comment]
可以把控制台打开看看是不是后端服务请求失败了，我之前是因为mysql没连接成功和你的现象一样

**Comment by ZhengZhongheng** [comment]
好的，谢谢，我再检查数据源等相关配置。

**Comment by ZhengZhongheng** [comment]
奇怪，mysql的用户metis及其3个表以及表数据都正常，还是不行。

**Comment by ZhengZhongheng** [comment]
不是DOCKER安装的，3306端口用 netstat -ntlp看了，也没有占用

**Comment by Jesyjun** [comment]
楼上的哥，问题解决了嘛，和您一样的问题

**Comment by linhai-meng** [comment]
请问这个问题，解决了吗？
