### ISSUE TITLE
启动服务端错误

### ISSUE THREAD

**Issue by ZhengZhongheng** [Tencent/Metis#46]
启动服务端程序，python /data/Metis/app/controller/manage.py runserver {ip}:{port}，
选择本机  127.0.0.1，端口 12350， 
运行后，浏览器 http://127.0.0.1:12350，报 "Page not found (404)“，
但是 lsof | grep 12350，可以看到处于监听状态。

**Comment by ZhengZhongheng** [comment]
![default](https://user-images.githubusercontent.com/45590585/49432829-8412cd00-f7eb-11e8-8c66-d85e8b3ce4df.png)

**Comment by ZhengZhongheng** [comment]
![default](https://user-images.githubusercontent.com/45590585/49433002-eff53580-f7eb-11e8-8cec-6de12ccb52b2.png)

**Comment by shilicqupt** [comment]
这个是api程序啊，/ path下没有对应的匹配，你可以把web程序起来看能不能读到数据

**Comment by ZhengZhongheng** [comment]
谢谢， 因为是虚机，服务器真实IP就是本机浏览器的机器，所以，WEB机器访问，就写 http://localhost:80，界面能正常出现，就是始终显示“加载中”。
