### ISSUE TITLE
关于样本构建的问题

### ISSUE THREAD

**Issue by zkybs** [Tencent/Metis#48]
样本构建应该是里面的核心环节，但项目里面没看到什么地方提及，所以想问下
1. metis里面有个曲线分类，然而不同的曲线可能只是存在比较小的差异性，比如两条曲线都比较光滑，类型差不多，但某一条曲线可能会出现比较小的凸点（属于正常值），这在前面整个类别的样本库里面其实是没有的，这个时候你们一般怎么解决呢？ 重新加入新曲线的正常样本？
2. 另一个问题关于异常样本的标记，因为实际发生异常时是一个段落，如果全部标记实际会降低效果的（比如异常的起始，或者中间的某些位置，其实是相对比较正常的），这个时候你们是怎么解决的呢？
3. 正常样本的使用，你们是进行了筛选？还是直接用某些曲线的正常值存入样本库？

**Comment by zr9558** [comment]
> 样本构建应该是里面的核心环节，但项目里面没看到什么地方提及，所以想问下
> 
> 1. metis里面有个曲线分类，然而不同的曲线可能只是存在比较小的差异性，比如两条曲线都比较光滑，类型差不多，但某一条曲线可能会出现比较小的凸点（属于正常值），这在前面整个类别的样本库里面其实是没有的，这个时候你们一般怎么解决呢？ 重新加入新曲线的正常样本？
> 2. 另一个问题关于异常样本的标记，因为实际发生异常时是一个段落，如果全部标记实际会降低效果的（比如异常的起始，或者中间的某些位置，其实是相对比较正常的），这个时候你们是怎么解决的呢？
> 3. 正常样本的使用，你们是进行了筛选？还是直接用某些曲线的正常值存入样本库？

1. Metis 的曲线分类集中在对曲线的整体形状分类，因为运维的数据通常来说都会有毛刺型，波峰波谷型等各种各样的曲线。在这种情况下，针对时间序列的值分布信息可以做出一些特征，例如分桶熵（binned entropy）等特征，用于区分时间序列的形状。如果某一条曲线的某个时间戳出现了一个小凸点，并且这个小凸点没有改变时间序列的整体形状和走势的话。一般来说，它和没有凸点的曲线可以看成是一类。如果样本库里面没有这类样本的话，建议人工标注，并添加这类样本，最后重新训练模型即可。
2. 异常的开始时间应该是需要标记的，通常来说，运维人员是需要在发生故障的初始阶段就要发现告警的，因此，初始阶段的标注工作是必要的。至于持续异常阶段（有可能持续几十分钟，几个小时等）就看业务的需要了，可以标注也可以不标注，根据自身业务的需要来标记即可。
3. 正常样本的选择：从海量正常样本中随机选择一部分即可，因为正常样本是非常多的。

**Comment by zkybs** [comment]
1. 对这个分类比较好奇，是首先分好类去寻找对应的模型；还是一个通用模型，然后根据 分桶熵 这样的分类特征，在模型训练时就实现了一种曲线区分，就好像加入了曲线id。
2. 之所以有`是否起始需要标记`，是因为我们在首先对数据进行了标注(工具不是很完善，通过划线的方式标注，所以跟异常衔接的一部分正常也标注了)，在样本筛选层叠加了一层iforest(针对具体项目做的特征工程)，性能是有比较大的提升的。我们通过观察，发现iforest主要是将 `起始正常值去除， 异常段落中间较正常的数据去除`。iforest对异常样本进行筛选，而这部分数据主要是我们标注上的不准确所带来的，所以想了解下你们是怎么解决的？
3. 正常样本的选择，其实和上面的情况差不多，iforest进行筛选，然后再加入库。实际操作中也发现，Iforest筛选出的正常样本对模型的效果提升也是比较明显的

**Comment by zr9558** [comment]
> 1. 对这个分类比较好奇，是首先分好类去寻找对应的模型；还是一个通用模型，然后根据 分桶熵 这样的分类特征，在模型训练时就实现了一种曲线区分，就好像加入了曲线id？
> 2. 之所以有`是否起始需要标记`，是因为我们在首先对数据进行了标注(工具不是很完善，通过划线的方式标注，所以跟异常衔接的一部分正常也标注了)，在样本筛选层叠加了一层iforest(针对具体项目做的特征工程)，性能是有比较大的提升的。我们通过观察，发现iforest主要是将 `起始正常值去除， 异常段落中间较正常的数据去除`。iforest对异常样本进行筛选，而这部分数据主要是我们标注上的不准确所带来的，所以想了解下你们是怎么解决的？
> 3. 正常样本的选择，其实和上面的情况差不多，iforest进行筛选，然后再加入库。实际操作中也发现，Iforest筛选出的正常样本对模型的效果提升也是比较明显的

1. 时间序列的分类和直接加入 ID 是截然不同的。这里我们使用的是统计特征+拟合特征+分类特征形成的通用模型，并没有事先进行曲线分类。当然，用分类特征来做曲线的分类是可以的，可以用 KMeans 算法来做。曲线分类的方法可以参考：[时间序列的表示与信息提取](https://zhuanlan.zhihu.com/p/39105270)，[时间序列的相似性](https://zhuanlan.zhihu.com/p/38130622)。也可以在 GOOGLE 搜索相应的论文进行查阅。
2. 靠人工的反复校验来解决样本的标注错误问题，样本标注一直是机器学习中的一个重要环节，例如图片标注行业，标注一幅图片是有一定的成本的。
