### ISSUE TITLE
关于具体有哪些公司使用这个框架？

### ISSUE THREAD

**Issue by qhwscream** [Tencent/Metis#51]
就是想问下，有没有具体的公司目前使用这个框架做实际项目？Metis具体的使用场景有哪些？

**Comment by wanghuaway** [comment]
使用场景请参考https://github.com/Tencent/Metis/blob/master/docs/usecase.md
常用于指标的异常检测

**Comment by qhwscream** [comment]
@wanghuaway 我看到这个了，我的意思是有没有更为详细的场景。

**Comment by wanghuaway** [comment]
你想用在哪些场景？   这个使用场景很广泛，涉及时序数据的异常检测，在监控告警、KPI指标检测等场景用的比较多
