### ISSUE TITLE
Docker安装部署时，run Docker 镜像的系统必须在是 64bit ？

### ISSUE THREAD

**Issue by blueliuyun** [Tencent/Metis#52]
[Metis__Docker_Install_64bit](https://blueliuyun.github.io/pic/Metis__Docker_Install_64bit__20190224113535.png)  -- successful 
![metis__docker_install_64bit__20190224113535](https://user-images.githubusercontent.com/6221934/53294895-a3d5f200-382a-11e9-992d-ed94bff6beea.png)

![_20190224115528](https://user-images.githubusercontent.com/6221934/53294918-1d6de000-382b-11e9-98dc-fa27848782c9.png)

[Metis__Docker_Install__32bit](https://github.com/blueliuyun/blueliuyun.github.io/blob/master/pic/Metis__Docker_Install__32bit__20190224113704.png)       -- failed 
![metis__docker_install__32bit__20190224113704](https://user-images.githubusercontent.com/6221934/53294896-a89aa600-382a-11e9-8f23-4e05612578c2.png)

如上图，在第一幅图示的 64bit 系统中 run 官方提供的镜像就顺利运行；参考doc中的 [docker 部署方法](https://github.com/Tencent/Metis/blob/master/docs/install.md#chapter-2) 。

请问上述情况是因为安装说明内提供的 3 个 docker image 是在 64 bit OS 环境下制作发布的吧？

**Comment by wanghuaway** [comment]
是的 需使用64位

**Comment by blueliuyun** [comment]
@wanghuaway thanks,
