### ISSUE TITLE
请问是否提供 2 维及以上多维的异常检测？  

### ISSUE THREAD

**Issue by blueliuyun** [Tencent/Metis#53]
![_20190224121202](https://user-images.githubusercontent.com/6221934/53295048-7179c400-382d-11e9-88fa-e301f45df211.png)

如上图，看上去效果很好，但仅有一维时序异常检测。请问是否会提供 2 维及以上多维的异常检测？  
因为有些异常工况，可能会考虑到多维时序在某一个时刻的综合特征，从而判断是否出故障。

**Comment by wanghuaway** [comment]
时间序列异常检测和多维分析是两种场景。
时间序列异常检测是对单指标内数据特征的分析
多维更多的是指标组合间

**Comment by blueliuyun** [comment]
@wanghuaway 谢谢您的回复。
