### ISSUE TITLE
libdetect.so GLIBC 版本问题

### ISSUE THREAD

**Issue by liuhaoXD** [Tencent/Metis#54]
libdetect.so 在加载时报错

```
/lib64/libc.so.6: version `GLIBC_2.14' not found
```
看上去这个 shared object 文件是在 glibc >= 2.14 环境下编译的，对于老平台都不兼容了。

请问能否提供一下 libdetect.so 的源码，或者提供一下使用低版本 glibc 编译得到的 so？

**Comment by wanghuaway** [comment]
so在编译时依赖c++11特性，glibc较低版本不支持
主要原因是xgb的编译
