### ISSUE TITLE
这个ini配置django可以起来，不过页面读取不到数据库内容，请问一下nginx里面是怎么配置的？

### ISSUE THREAD

**Issue by Jesyjun** [Tencent/Metis#58]
这个ini配置django可以起来，不过页面读取不到数据库内容，请问一下nginx里面是怎么配置的？

_Originally posted by @Jesyjun in https://github.com/Tencent/Metis/issues/27#issuecomment-481080459_

**Comment by wanghuaway** [comment]
server {
        listen       80;
        root /*/uweb/dist;
        location / {
                add_header Cache-Control max-age=0;
                gzip on;
                gzip_min_length 1k;
                gzip_buffers 16 64k;
                gzip_http_version 1.1;
                gzip_comp_level 6;
                gzip_types text/plain application/x-javascript text/css application/xml;
                gzip_vary on;
                    try_files $uri $uri/ /index.html;
        }

        location /index.html {
                add_header Cache-Control 'no-store';
        }
    }

nginx参考下这个配置

**Comment by Jesyjun** [comment]
nginx这样可以把静态页面起起来，uwsgi也可以把django起起来，现在页面一直是加载中，读取不了数据库的值，3306也没有占用。
