### ISSUE TITLE
打开网页提示404，请帮忙分析一下

### ISSUE THREAD

**Issue by viking714** [Tencent/Metis#69]
之前按照提示安装下来，最后运行以下命令，python /usr/local/src/Metis/Metis-master/app/controller/manage.py runserver 192.168.206.133:8090
也没有报错，看起来挺正常，如下：

System check identified no issues (0 silenced).
July 10, 2019 - 15:42:07
Django version 1.10.3, using settings 'settings.settings'
Starting development server at http://192.168.206.133:8090/
Quit the server with CONTROL-C.
Not Found: /
[10/Jul/2019 15:42:38] "GET / HTTP/1.1" 404 3708
Not Found: /favicon.ico
[10/Jul/2019 15:42:38] "GET /favicon.ico HTTP/1.1" 404 3741
Not Found: /favicon.ico
[10/Jul/2019 15:42:38] "GET /favicon.ico HTTP/1.1" 404 3741

但是打开浏览器，http://192.168.206.133:8090/
却出现以下内容：

Page not found (404)
Request Method: 	GET
Request URL: 	http://192.168.206.133:8090/

Using the URLconf defined in settings.urls, Django tried these URL patterns, in this order:

    ^SearchAnomaly$ [name='search_anomaly']
    ^ImportSample$ [name='import_sample']
    ^UpdateSample$ [name='update_sample']
    ^QuerySample$ [name='query_sample']
    ^DeleteSample$ [name='delete_sample']
    ^CountSample$ [name='count_sample']
    ^UpdateAnomaly$ [name='update_anomaly']
    ^DownloadSample/ [name='download_sample']
    ^QueryTrain$ [name='query_train_task']
    ^QueryTrainSource$ [name='query_train_source']
    ^DeleteTrain$ [name='delete_train_task']
    ^Train$ [name='train']
    ^PredictRate$ [name='predict_rate']
    ^PredictValue$ [name='predict_value']

The current URL, , didn't match any of these.
请问这个是什么引起的，万分感谢。

**Comment by MichaelJRY** [comment]
http://172.16.148.133:8080/SearchAnomaly
因为django没有存在的访问路由会报404.这个服务已经正常了。可以按照我上面的连接来验证，路由下的返回。
