### ISSUE TITLE
能否自定义上报的数据点粒度

### ISSUE THREAD

**Issue by aaron077** [Tencent/Metis#71]
现在的API接口，是当前检测时间窗口选取为3小时，每分钟1个数据点，即窗口值为180。
能不能支持自定义上报的数据点，比如每5分钟一个数据点？
谢谢

**Comment by aaron077** [comment]
换句话说，如果时间间隔是5分钟，怎么对数据做必要的改造？窗口值还是按照180，那就是15个小时的数据。。
但是这样的话，web端的图表展示就会有问题吧，因为他的横坐标是按每分钟的？
我没去实际验证过，多多指教。

**Comment by wanghuaway** [comment]
如果时间间隔是五分钟的 一般采取插值的方式来做 采用临近值补充 这样的好处是可复用默认模型，不需要重新训练；
如果想改成5分钟的 就在后台参数中修改window值为36，同时对应训练一版5分钟间隔的模型文件，web端也对窗口做对应调整

**Comment by aaron077** [comment]
> 如果时间间隔是五分钟的 一般采取插值的方式来做 采用临近值补充 这样的好处是可复用默认模型，不需要重新训练；
> 如果想改成5分钟的 就在后台参数中修改window值为36，同时对应训练一版5分钟间隔的模型文件，web端也对窗口做对应调整

今天在api调用时window改为36来验证，正常样本的样本数据通过API跑测试没问题，返回也是说正常。但是当我修改待检测点的数据时，比如原值为4800，我修改为3800或者5800，都会报错。
报错信息如下: File "/metis/time_series_detector/feature/fitting_features.py", line 216, in time_series_periodic_features
    periodic_features.append(min(max(data_a[w - 1:w + step]) - data_a[-1], 0))
ValueError: max() arg is an empty sequence。

正常的样本数据如下:
{
    "viewId":"8018",
    "viewName":"cap_test",
    "attrId":"18018",
    "attrName":"cap_18018",
    "window":36,
    "time":"2019-06-06 10:00:00",
    "dataC":"4410,4452,4450,4414,4456,4562,4578,4608,4594,4588,4656,4640,4644,4658,4670,4750,4744,4726,4752,4754,4728,4324,3154,4804,4774,4742,4720,4760,4762,4768,4766,4776,4717,4687,4656,4620,4625,4676,4723,4655,4610,4608,4587,4561,4570,4567,4538,4525,4567,4537,4506,4465,4427,4486,4447,4408,4309,4388,4370,4366,4334,4368,4352,4370,4374,4411,4422,4440,4434,4389,4473,4501,4509",
    "dataB":"4556,4573,4589,4622,4653,4675,4728,4752,4710,4719,4758,4776,4750,4817,4813,4832,4863,4855,4841,4875,4831,4825,4875,4898,4888,4927,4914,4885,4865,4894,4892,4899,4838,4801,4774,4757,4765,4806,4802,4742,4700,4700,4691,4688,4715,4662,4629,4659,4665,4624,4589,4564,4605,4555,4511,4499,4523,4533,4531,4504,4487,4489,4522,4541,4523,4524,4504,4478,4471,4529,4568,4604,4584",
    "dataA":"4580,4540,4530,4600,4680,4690,4760,4770,4760,4800,4820,4790,4760,4810,4800,4810,4810,4830,4800,4860,4810,4760,4840,4880,4900,4870,4820,4880,4930,4910,4870,4880,4850,4820,4830,4810,4800"
}
返回ret:1。没问题。。
现在只要把dataA的最后一个值(也就是待检测点)4800,修改为3800或者5800，都会报错。。

这是在特征拟合的时候报的错,具体是什么原因呢？请指教

**Comment by aaron077** [comment]
详细报错信息如下:
Internal Server Error: /PredictValue
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./api/views.py", line 20, in f
    return_dict = func(request)
  File "./api/views.py", line 90, in predict_value
    return detect_service.value_predict(json.loads(request.body))
  File "/metis/app/service/time_series_detector/detect_service.py", line 131, in value_predict
    ret_code, ret_data = self.detect_obj.value_predict(data)
  File "/metis/time_series_detector/detect.py", line 94, in value_predict
    xgb_result = self.supervised_obj.predict(time_series, window, model_name)
  File "/metis/time_series_detector/algorithm/xgboosting.py", line 159, in predict
    features.extend(feature_service.extract_features(X, window))
  File "/metis/time_series_detector/feature/feature_service.py", line 39, in extract_features
    f_features = fitting_features.get_fitting_features(normalized_split_time_series)
  File "/metis/time_series_detector/feature/fitting_features.py", line 229, in get_fitting_features
    fitting_features.extend(time_series_periodic_features(x_list[0], x_list[1], x_list[2], x_list[3], x_list[4]))
  File "/metis/time_series_detector/feature/fitting_features.py", line 216, in time_series_periodic_features
    periodic_features.append(min(max(data_a[w - 1:w + step]) - data_a[-1], 0))
ValueError: max() arg is an empty sequence

>

**Comment by wanghuaway** [comment]
是这样的  整个检测逻辑分2层 第一层无监督 第二层有监督，整体的检测顺序是第一层检测为异常的数据才会传递给第二层
第一层：无监督检测的多数算法不会强校验窗口，这时候如果是正常数据就会检测通过，不进行第二层有监督；
第二层：xgb训练的模型是严格和窗口相关的，一个模型只适配一个窗口值，所以如果没有重新训练模型就会报错，需要重新用对应的窗口训练。
