### ISSUE TITLE
请问一下率值检测和量值检测的定义

### ISSUE THREAD

**Issue by zhanghao1949** [Tencent/Metis#77]
关于率值检测和量值检测有两个问题，请教一下：
1、率值检测这个名称是否是自己定义的，因为主要用于检测成功率所以称之为率值，还是引用的专业名词？量值检测这个名词是基于什么定义的？
2、调用量值检测API传入浮点数的话，会报异常；量值检测接口为什么不支持浮点数，这是基于什么考虑？

**Comment by wanghuaway** [comment]
量值检测主要用途可以用在KPI指标的检测，偏向于业务的特性数值上报，诸如登陆量、成交量、请求数之类，所以建议取整型，传浮点数加上一层取整转换也可以可以的；
率值检测主要用于成功率的检测，从运维经验上定义的名字
