### ISSUE TITLE
ubuntu安装不成功

### ISSUE THREAD

**Issue by doycode** [Tencent/Metis#78]
ubuntu16.04 LTS
按方式2通过docker部署，执行docker ps，只有metis-web正常启动
PS: 8080端口已开

**Comment by doycode** [comment]
安装方式1中说推荐centos，是因为系统的问题吗，求大佬解惑

**Comment by marvelcaton** [comment]
@doycode ubuntu上要执行 service mysql stop，再启动metis-db，然后metis-svr需要检查一下端口8080是否被占用 netstat -anp | grep 8080，再启动metis-svr
