### ISSUE TITLE
docker安装的方式支持mac吗？

### ISSUE THREAD

**Issue by bearomance** [Tencent/Metis#79]
在mac本地运行后显示成功，但是访问地址说拒绝连接，如下图

![4B3CA7B7-4F45-496A-BFF6-B597C094CC22](https://user-images.githubusercontent.com/11454633/63845508-a32a3e00-c9bc-11e9-86a2-9046ae5595aa.png)

**Comment by marvelcaton** [comment]
@bearomance 访问127.0.0.1:80

**Comment by windcaller31** [comment]
访问 127.0.0.1:80 也不行啊
