### ISSUE TITLE
docker启动报错

### ISSUE THREAD

**Issue by libp** [Tencent/Metis#8]
Step 1 : FROM zhiyunmetis/metis-full
 ---> 1622911b6c2e
Step 2 : WORKDIR /metis
 ---> Using cache
 ---> b48ed2668c4c
Step 3 : ADD . /metis
 ---> Using cache
 ---> 6015ba1b8dfa
Step 4 : EXPOSE 80
 ---> Using cache
 ---> dc693d43038a
Step 5 : EXPOSE 8080
 ---> Using cache
 ---> e1c6442aff3d
Step 6 : RUN chmod +x /metis/init.sh
 ---> Using cache
 ---> a757a442b401
Step 7 : CMD /bin/sh /metis/init.sh
 ---> Using cache
 ---> 508e0c2c741b
Successfully built 508e0c2c741b
/usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint romantic_blackwell (41ec0f0ec4e29ceddc7ea463743ac87a349c8ccaee52d2c2fbae54eff099da2a): iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.17.0.2:8080 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1).
[root@compute1 docker]# docker run -i -t -p80:80 -p8080:8080 local/metis-demo:1.0
/usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint pedantic_varahamihira (296d662bd2ef5a6d06613e93f356cc2f199129512cebdcbc09a35e2c244fc289): iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.17.0.2:8080 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1).
[root@compute1 docker]#

**Comment by wanghuaway** [comment]
此报错看起来是防火墙限制，使用的是什么版本系统？ 是否有配置一些自己公司的限制策略？  请检查下iptables

**Comment by libp** [comment]
@wanghuaway iptables卸载了。这是在物理机上运行这个容器，物理机之前的网络用的是桥接模式

**Comment by libp** [comment]
搞定了。IP换成本机的IP就行
